#############################################################################
# Makefile for building: ELISAREADER
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  ../../Desktop/ELISAREADER V1.1/ELISAREADER.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ../../Desktop/ELISAREADER\ V1.1/ELISAREADER.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_CHARTS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_XLSX_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../../Desktop/ELISAREADER\ V1.1 -I. -isystem /usr/local/include -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCharts -isystem /usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWebKitWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWebKit -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXlsx -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSql -isystem /usr/include/arm-linux-gnueabihf/qt5/QtQml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ELISAREADER1.0.0
DISTDIR = /home/pi/git/build-ELISAREADER-Desktop-Debug/.tmp/ELISAREADER1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath-link,/usr/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L/usr/local/lib -lwiringPi -lQt5Charts -lQt5PrintSupport -lQt5WebKitWidgets -lQt5Widgets -lQt5WebKit -lQt5Xlsx -lQt5Gui -lQt5Sql -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lpthread -latomic 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../../Desktop/ELISAREADER\ V1.1/main.cpp \
		../../Desktop/ELISAREADER\ V1.1/mainwindow.cpp \
		../../Desktop/ELISAREADER\ V1.1/keyboard.cpp \
		../../Desktop/ELISAREADER\ V1.1/ADS1263.cpp \
		../../Desktop/ELISAREADER\ V1.1/DEV_Config.cpp \
		../../Desktop/ELISAREADER\ V1.1/pi2c.cpp \
		../../Desktop/ELISAREADER\ V1.1/regressionline.cpp \
		../../Desktop/ELISAREADER\ V1.1/dialog.cpp \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.cpp \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.cpp \
		../../Desktop/ELISAREADER\ V1.1/ap.cpp \
		../../Desktop/ELISAREADER\ V1.1/integration.cpp \
		../../Desktop/ELISAREADER\ V1.1/interpolation.cpp \
		../../Desktop/ELISAREADER\ V1.1/linalg.cpp \
		../../Desktop/ELISAREADER\ V1.1/optimization.cpp \
		../../Desktop/ELISAREADER\ V1.1/solvers.cpp \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.cpp moc_mainwindow.cpp \
		moc_keyboard.cpp \
		moc_dialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		keyboard.o \
		ADS1263.o \
		DEV_Config.o \
		pi2c.o \
		regressionline.o \
		dialog.o \
		alglibinternal.o \
		alglibmisc.o \
		ap.o \
		integration.o \
		interpolation.o \
		linalg.o \
		optimization.o \
		solvers.o \
		specialfunctions.o \
		moc_mainwindow.o \
		moc_keyboard.o \
		moc_dialog.o
DIST          = /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xlsx.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xlsx_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		../../Desktop/ELISAREADER V1.1/.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		../../Desktop/ELISAREADER V1.1/ELISAREADER.pro ../../Desktop/ELISAREADER\ V1.1/mainwindow.h \
		../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		../../Desktop/ELISAREADER\ V1.1/ADS1263.h \
		../../Desktop/ELISAREADER\ V1.1/DEV_Config.h \
		../../Desktop/ELISAREADER\ V1.1/pi2c.h \
		../../Desktop/ELISAREADER\ V1.1/regressionline.h \
		../../Desktop/ELISAREADER\ V1.1/dialog.h \
		../../Desktop/ELISAREADER\ V1.1/HL7Exception.h \
		../../Desktop/ELISAREADER\ V1.1/hl7mllp.h \
		../../Desktop/ELISAREADER\ V1.1/HL7Object.h \
		../../Desktop/ELISAREADER\ V1.1/hl7socket.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h \
		../../Desktop/ELISAREADER\ V1.1/interpolation.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/stdafx.h ../../Desktop/ELISAREADER\ V1.1/main.cpp \
		../../Desktop/ELISAREADER\ V1.1/mainwindow.cpp \
		../../Desktop/ELISAREADER\ V1.1/keyboard.cpp \
		../../Desktop/ELISAREADER\ V1.1/ADS1263.cpp \
		../../Desktop/ELISAREADER\ V1.1/DEV_Config.cpp \
		../../Desktop/ELISAREADER\ V1.1/pi2c.cpp \
		../../Desktop/ELISAREADER\ V1.1/regressionline.cpp \
		../../Desktop/ELISAREADER\ V1.1/dialog.cpp \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.cpp \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.cpp \
		../../Desktop/ELISAREADER\ V1.1/ap.cpp \
		../../Desktop/ELISAREADER\ V1.1/integration.cpp \
		../../Desktop/ELISAREADER\ V1.1/interpolation.cpp \
		../../Desktop/ELISAREADER\ V1.1/linalg.cpp \
		../../Desktop/ELISAREADER\ V1.1/optimization.cpp \
		../../Desktop/ELISAREADER\ V1.1/solvers.cpp \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.cpp
QMAKE_TARGET  = ELISAREADER
DESTDIR       = 
TARGET        = ELISAREADER


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_keyboard.h ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../../Desktop/ELISAREADER\ V1.1/ELISAREADER.pro /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xlsx.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xlsx_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		../../Desktop/ELISAREADER\ V1.1/ELISAREADER.pro \
		/usr/lib/arm-linux-gnueabihf/libQt5Charts.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5PrintSupport.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Xlsx.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Sql.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Qml.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Network.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile ../../Desktop/ELISAREADER\ V1.1/ELISAREADER.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xlsx.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xlsx_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf:
../../Desktop/ELISAREADER\ V1.1/ELISAREADER.pro:
/usr/lib/arm-linux-gnueabihf/libQt5Charts.prl:
/usr/lib/arm-linux-gnueabihf/libQt5PrintSupport.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Xlsx.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Sql.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Qml.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Network.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../../Desktop/ELISAREADER\ V1.1/ELISAREADER.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../../Desktop/ELISAREADER\ V1.1/mainwindow.h ../../Desktop/ELISAREADER\ V1.1/keyboard.h ../../Desktop/ELISAREADER\ V1.1/ADS1263.h ../../Desktop/ELISAREADER\ V1.1/DEV_Config.h ../../Desktop/ELISAREADER\ V1.1/pi2c.h ../../Desktop/ELISAREADER\ V1.1/regressionline.h ../../Desktop/ELISAREADER\ V1.1/dialog.h ../../Desktop/ELISAREADER\ V1.1/HL7Exception.h ../../Desktop/ELISAREADER\ V1.1/hl7mllp.h ../../Desktop/ELISAREADER\ V1.1/HL7Object.h ../../Desktop/ELISAREADER\ V1.1/hl7socket.h ../../Desktop/ELISAREADER\ V1.1/alglibinternal.h ../../Desktop/ELISAREADER\ V1.1/alglibmisc.h ../../Desktop/ELISAREADER\ V1.1/ap.h ../../Desktop/ELISAREADER\ V1.1/integration.h ../../Desktop/ELISAREADER\ V1.1/interpolation.h ../../Desktop/ELISAREADER\ V1.1/linalg.h ../../Desktop/ELISAREADER\ V1.1/optimization.h ../../Desktop/ELISAREADER\ V1.1/solvers.h ../../Desktop/ELISAREADER\ V1.1/specialfunctions.h ../../Desktop/ELISAREADER\ V1.1/stdafx.h $(DISTDIR)/
	$(COPY_FILE) --parents ../../Desktop/ELISAREADER\ V1.1/main.cpp ../../Desktop/ELISAREADER\ V1.1/mainwindow.cpp ../../Desktop/ELISAREADER\ V1.1/keyboard.cpp ../../Desktop/ELISAREADER\ V1.1/ADS1263.cpp ../../Desktop/ELISAREADER\ V1.1/DEV_Config.cpp ../../Desktop/ELISAREADER\ V1.1/pi2c.cpp ../../Desktop/ELISAREADER\ V1.1/regressionline.cpp ../../Desktop/ELISAREADER\ V1.1/dialog.cpp ../../Desktop/ELISAREADER\ V1.1/alglibinternal.cpp ../../Desktop/ELISAREADER\ V1.1/alglibmisc.cpp ../../Desktop/ELISAREADER\ V1.1/ap.cpp ../../Desktop/ELISAREADER\ V1.1/integration.cpp ../../Desktop/ELISAREADER\ V1.1/interpolation.cpp ../../Desktop/ELISAREADER\ V1.1/linalg.cpp ../../Desktop/ELISAREADER\ V1.1/optimization.cpp ../../Desktop/ELISAREADER\ V1.1/solvers.cpp ../../Desktop/ELISAREADER\ V1.1/specialfunctions.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../../Desktop/ELISAREADER\ V1.1/mainwindow.ui ../../Desktop/ELISAREADER\ V1.1/keyboard.ui ../../Desktop/ELISAREADER\ V1.1/dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_keyboard.cpp moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_keyboard.cpp moc_dialog.cpp
moc_mainwindow.cpp: ../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		../../Desktop/ELISAREADER\ V1.1/pi2c.h \
		../../Desktop/ELISAREADER\ V1.1/ADS1263.h \
		../../Desktop/ELISAREADER\ V1.1/DEV_Config.h \
		../../Desktop/ELISAREADER\ V1.1/regressionline.h \
		../../Desktop/ELISAREADER\ V1.1/dialog.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/interpolation.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h \
		../../Desktop/ELISAREADER\ V1.1/plotting.h \
		../../Desktop/ELISAREADER\ V1.1/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/git/build-ELISAREADER-Desktop-Debug/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I'/home/pi/Desktop/ELISAREADER V1.1' -I/usr/local/include -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtCharts -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWebKitWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtWebKit -I/usr/include/arm-linux-gnueabihf/qt5/QtXlsx -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtSql -I/usr/include/arm-linux-gnueabihf/qt5/QtQml -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ../../Desktop/ELISAREADER\ V1.1/mainwindow.h -o moc_mainwindow.cpp

moc_keyboard.cpp: ../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/git/build-ELISAREADER-Desktop-Debug/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I'/home/pi/Desktop/ELISAREADER V1.1' -I/usr/local/include -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtCharts -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWebKitWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtWebKit -I/usr/include/arm-linux-gnueabihf/qt5/QtXlsx -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtSql -I/usr/include/arm-linux-gnueabihf/qt5/QtQml -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ../../Desktop/ELISAREADER\ V1.1/keyboard.h -o moc_keyboard.cpp

moc_dialog.cpp: ../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		../../Desktop/ELISAREADER\ V1.1/regressionline.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/interpolation.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h \
		../../Desktop/ELISAREADER\ V1.1/dialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/git/build-ELISAREADER-Desktop-Debug/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I'/home/pi/Desktop/ELISAREADER V1.1' -I/usr/local/include -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtCharts -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWebKitWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtWebKit -I/usr/include/arm-linux-gnueabihf/qt5/QtXlsx -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtSql -I/usr/include/arm-linux-gnueabihf/qt5/QtQml -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ../../Desktop/ELISAREADER\ V1.1/dialog.h -o moc_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_keyboard.h ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_keyboard.h ui_dialog.h
ui_mainwindow.h: ../../Desktop/ELISAREADER\ V1.1/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../../Desktop/ELISAREADER\ V1.1/mainwindow.ui -o ui_mainwindow.h

ui_keyboard.h: ../../Desktop/ELISAREADER\ V1.1/keyboard.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../../Desktop/ELISAREADER\ V1.1/keyboard.ui -o ui_keyboard.h

ui_dialog.h: ../../Desktop/ELISAREADER\ V1.1/dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../../Desktop/ELISAREADER\ V1.1/dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../../Desktop/ELISAREADER\ V1.1/main.cpp ../../Desktop/ELISAREADER\ V1.1/mainwindow.h \
		../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		../../Desktop/ELISAREADER\ V1.1/pi2c.h \
		../../Desktop/ELISAREADER\ V1.1/ADS1263.h \
		../../Desktop/ELISAREADER\ V1.1/DEV_Config.h \
		../../Desktop/ELISAREADER\ V1.1/regressionline.h \
		../../Desktop/ELISAREADER\ V1.1/dialog.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/interpolation.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h \
		../../Desktop/ELISAREADER\ V1.1/plotting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../../Desktop/ELISAREADER\ V1.1/main.cpp

mainwindow.o: ../../Desktop/ELISAREADER\ V1.1/mainwindow.cpp ../../Desktop/ELISAREADER\ V1.1/mainwindow.h \
		../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		../../Desktop/ELISAREADER\ V1.1/pi2c.h \
		../../Desktop/ELISAREADER\ V1.1/ADS1263.h \
		../../Desktop/ELISAREADER\ V1.1/DEV_Config.h \
		../../Desktop/ELISAREADER\ V1.1/regressionline.h \
		../../Desktop/ELISAREADER\ V1.1/dialog.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/interpolation.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h \
		../../Desktop/ELISAREADER\ V1.1/plotting.h \
		ui_mainwindow.h \
		../../Desktop/ELISAREADER\ V1.1/hl7mllp.h \
		../../Desktop/ELISAREADER\ V1.1/hl7socket.h \
		../../Desktop/ELISAREADER\ V1.1/HL7Exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../../Desktop/ELISAREADER\ V1.1/mainwindow.cpp

keyboard.o: ../../Desktop/ELISAREADER\ V1.1/keyboard.cpp ../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o ../../Desktop/ELISAREADER\ V1.1/keyboard.cpp

ADS1263.o: ../../Desktop/ELISAREADER\ V1.1/ADS1263.cpp ../../Desktop/ELISAREADER\ V1.1/ADS1263.h \
		../../Desktop/ELISAREADER\ V1.1/DEV_Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ADS1263.o ../../Desktop/ELISAREADER\ V1.1/ADS1263.cpp

DEV_Config.o: ../../Desktop/ELISAREADER\ V1.1/DEV_Config.cpp ../../Desktop/ELISAREADER\ V1.1/DEV_Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DEV_Config.o ../../Desktop/ELISAREADER\ V1.1/DEV_Config.cpp

pi2c.o: ../../Desktop/ELISAREADER\ V1.1/pi2c.cpp ../../Desktop/ELISAREADER\ V1.1/pi2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pi2c.o ../../Desktop/ELISAREADER\ V1.1/pi2c.cpp

regressionline.o: ../../Desktop/ELISAREADER\ V1.1/regressionline.cpp ../../Desktop/ELISAREADER\ V1.1/regressionline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o regressionline.o ../../Desktop/ELISAREADER\ V1.1/regressionline.cpp

dialog.o: ../../Desktop/ELISAREADER\ V1.1/dialog.cpp ../../Desktop/ELISAREADER\ V1.1/dialog.h \
		../../Desktop/ELISAREADER\ V1.1/keyboard.h \
		../../Desktop/ELISAREADER\ V1.1/regressionline.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/interpolation.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o ../../Desktop/ELISAREADER\ V1.1/dialog.cpp

alglibinternal.o: ../../Desktop/ELISAREADER\ V1.1/alglibinternal.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alglibinternal.o ../../Desktop/ELISAREADER\ V1.1/alglibinternal.cpp

alglibmisc.o: ../../Desktop/ELISAREADER\ V1.1/alglibmisc.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alglibmisc.o ../../Desktop/ELISAREADER\ V1.1/alglibmisc.cpp

ap.o: ../../Desktop/ELISAREADER\ V1.1/ap.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ap.o ../../Desktop/ELISAREADER\ V1.1/ap.cpp

integration.o: ../../Desktop/ELISAREADER\ V1.1/integration.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integration.o ../../Desktop/ELISAREADER\ V1.1/integration.cpp

interpolation.o: ../../Desktop/ELISAREADER\ V1.1/interpolation.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/interpolation.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/integration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interpolation.o ../../Desktop/ELISAREADER\ V1.1/interpolation.cpp

linalg.o: ../../Desktop/ELISAREADER\ V1.1/linalg.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linalg.o ../../Desktop/ELISAREADER\ V1.1/linalg.cpp

optimization.o: ../../Desktop/ELISAREADER\ V1.1/optimization.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/optimization.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimization.o ../../Desktop/ELISAREADER\ V1.1/optimization.cpp

solvers.o: ../../Desktop/ELISAREADER\ V1.1/solvers.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/solvers.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h \
		../../Desktop/ELISAREADER\ V1.1/linalg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o solvers.o ../../Desktop/ELISAREADER\ V1.1/solvers.cpp

specialfunctions.o: ../../Desktop/ELISAREADER\ V1.1/specialfunctions.cpp ../../Desktop/ELISAREADER\ V1.1/stdafx.h \
		../../Desktop/ELISAREADER\ V1.1/specialfunctions.h \
		../../Desktop/ELISAREADER\ V1.1/ap.h \
		../../Desktop/ELISAREADER\ V1.1/alglibinternal.h \
		../../Desktop/ELISAREADER\ V1.1/alglibmisc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specialfunctions.o ../../Desktop/ELISAREADER\ V1.1/specialfunctions.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_keyboard.o: moc_keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboard.o moc_keyboard.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ELISAREADER/bin || mkdir -p $(INSTALL_ROOT)/opt/ELISAREADER/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ELISAREADER/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ELISAREADER/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ELISAREADER/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

